# Generated by Django 3.0.7 on 2020-09-03 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broadapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broad',
            old_name='profile',
            new_name='user',
        ),
    ]
