# Generated by Django 3.0.7 on 2020-09-08 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Broad',
            new_name='broad',
        ),
    ]
