# Generated by Django 3.0.7 on 2020-09-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broad', '0002_auto_20200908_0619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broad',
            options={'ordering': ['-id']},
        ),
    ]
