# Generated by Django 3.0.7 on 2020-09-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broad', '0003_auto_20200908_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='broad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
