# Generated by Django 3.0.7 on 2020-09-08 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broad', '0004_broad_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broad',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='broad',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='broad.Comment'),
        ),
    ]
